steps:

-   id: "Rodando docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose:latest'
    args: ['-f','docker-compose.prod.yaml','up','-d']

#adicione este step depois do up -d

-   id: "Chown in /var/www"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec','-u','root','-t','app','chown','-R','www-data:www-data','/var/www']

-   id: "Rodando docker ps"
    name: 'gcr.io/cloud-builders/docker'
    args: ['ps']
